/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class PlayNúmeros extends javax.swing.JFrame {

    /**
     * Creates new form PlayNúmeros
     */
    public PlayNúmeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSoma = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnVezes = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Play Números");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 111, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123SMART_LOGO.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnSoma.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnSoma.setText("Soma");
        btnSoma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });

        btnMenos.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnMenos.setText("Subtração");
        btnMenos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnVezes.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnVezes.setText("Multiplição");
        btnVezes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVezesActionPerformed(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnDiv.setText("Divisão");
        btnDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Tente acertar o resultado das operações matemáticas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        // TODO add your handling code here:
        int aleatorio = ((int)(Math.random()*1000));
        int aleatorio2 = ((int)(Math.random()*1000));
        int soma = aleatorio + aleatorio2;
        int numero = Integer.parseInt(JOptionPane.showInputDialog(null, aleatorio + " + " + aleatorio2 + " = "));
        
       if(numero!=soma){
           JOptionPane.showMessageDialog(null, "Que pena, Não foi dessa vez!", "Resultado", JOptionPane.PLAIN_MESSAGE);
            JOptionPane.showMessageDialog(null, "O resultado certo era: " + soma, "Resposta", JOptionPane.PLAIN_MESSAGE); 
        }else if(numero==soma){
       
           JOptionPane.showMessageDialog(null, "Parabéns, você acertou!", "Resultado", JOptionPane.PLAIN_MESSAGE);
         
        }
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        MenuDeNavegação tela2 = new MenuDeNavegação();
        tela2.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
        int aleatorio3 = ((int)(Math.random()*1000));
        int aleatorio4 = ((int)(Math.random()*1000));
        int menos = aleatorio3 - aleatorio4;
        JOptionPane.showMessageDialog(null, "Não se esqueça de colocar o sinal de menos se o resultado for negativo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        int numero2 = Integer.parseInt(JOptionPane.showInputDialog(null, aleatorio3 + " - " + aleatorio4 + " = "));
        
       if(numero2!=menos){
           JOptionPane.showMessageDialog(null, "Que pena, Não foi dessa vez!", "Resultado", JOptionPane.PLAIN_MESSAGE);
           JOptionPane.showMessageDialog(null, "O resultado certo era: " + menos, "Resposta", JOptionPane.PLAIN_MESSAGE); 
        }else if(numero2==menos){
       
           JOptionPane.showMessageDialog(null, "Parabéns, você acertou!", "Resultado", JOptionPane.PLAIN_MESSAGE);
         
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVezesActionPerformed
        // TODO add your handling code here:
        int aleatorio5 = ((int)(Math.random()*1000));
        int aleatorio6 = ((int)(Math.random()*1000));
        int vezes = aleatorio5 * aleatorio6;
        int numero3 = Integer.parseInt(JOptionPane.showInputDialog(null, aleatorio5 + " x " + aleatorio6 + " = "));
        
       if(numero3!=vezes){
           JOptionPane.showMessageDialog(null, "Que pena, Não foi dessa vez!", "Resultado", JOptionPane.PLAIN_MESSAGE);
           JOptionPane.showMessageDialog(null, "O resultado certo era: " + vezes, "Resposta", JOptionPane.PLAIN_MESSAGE); 
        }else if(numero3==vezes){
       
           JOptionPane.showMessageDialog(null, "Parabéns, você acertou!", "Resultado", JOptionPane.PLAIN_MESSAGE);
         
        }
    }//GEN-LAST:event_btnVezesActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        int aleatorio7 = ((int)(Math.random()*1000));
        int aleatorio8 = ((int)(Math.random()*10));
        int div = aleatorio7 / aleatorio8;
        JOptionPane.showMessageDialog(null, "Se o resultado for número com virgula, coloque só o número que está antes da virgula, (exemplo: se o número for 17,34, coloque só 17).", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        Double numero4 = Double.parseDouble(JOptionPane.showInputDialog(null, aleatorio7 + " / " + aleatorio8 + " = "));
        
       if(numero4!=div){
           JOptionPane.showMessageDialog(null, "Que pena, Não foi dessa vez!", "Resultado", JOptionPane.PLAIN_MESSAGE);
           JOptionPane.showMessageDialog(null, "O resultado certo era: " + div, "Resposta", JOptionPane.PLAIN_MESSAGE); 
        }else if(numero4==div){
       
           JOptionPane.showMessageDialog(null, "Parabéns, você acertou!", "Resultado", JOptionPane.PLAIN_MESSAGE);
         
        }
    }//GEN-LAST:event_btnDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayNúmeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayNúmeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayNúmeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayNúmeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayNúmeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnVezes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
